title: sourpit
baseURL: "https://sourpit.github.io/blog/"
theme: 'hugo-bearblog'

enableRobotsTXT: true

params:
  description: "muh blog"
  author: sourpit
  images:
    - cover.png
  favicon: favicon.ico
  mainSections:
    - posts
    - notes

# theme params
DisableLanguageSwitch: true
TocOpen: true
TocSide: right
EnableInstantClick: false
EnableImageZoom: true
ShowShareButtons: true
ShareButtons:
  - twitter
ShowReadingTime: true
ShowWordCount: true
ShowCodeCopyButtons: true
ShowPostNavLinks: true
Email: stinkypits@waifu.club

permalinks:
  notes: /:section/:year/:month/:slugorfilename

# prefer feed.xml rather than index.xml
outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

menu:
  main:
    - name: /posts
      url: /posts/
      weight: 1
    - name: /notes
      url: /notes/
      weight: 2
    - name: /feed
      url: /feed.xml
      weight: 3

languages:
  en:
    languageName: "English"

markup:
  highlight:
    style: friendly
    lineNos: true
    lineNumbersInTable: false
    codeFences: true
