title: sourpit
baseURL: "https://sourpit.github.io/blog/"
theme: hugo-bearblog

enableRobotsTXT: true
enableEmoji: false

params:
  description: "muh blog"
  author: sourpit
  images:
    - cover.png
  favicon: favicon.ico
  mainSections:
    - posts
    - notes

# theme params
DisableLanguageSwitch: true
TocOpen: true
TocSide: right
EnableInstantClick: false
EnableImageZoom: true
ShowShareButtons: true
ShareButtons:
  - twitter
ShowReadingTime: true
ShowWordCount: true
ShowCodeCopyButtons: true
ShowPostNavLinks: true
Email: stinkypits@waifu.club

socialIcons:
  - name: github-simple
    url: "https://github.com/sourpit"
  - name: rss-simple
    url: "feed.xml"

homeInfoParams:
  Title: "sourpit"
  Content: |
    bunch of stuff i'd try will be posted in here.

permalinks:
  notes: /:section/:year/:month/:slugorfilename

# prefer feed.xml rather than index.xml
outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

menu:
  main:
    - name: Posts
      url: /posts/
      weight: 1
    - name: Notes
      url: /notes/
      weight: 2
    - name: Archives
      url: /archives/
      weight: 3

languages:
  en:
    languageName: "English"
  id:
    languageName: "Bahasa Indonesia"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false
